import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  wikiSidebar: [
    "wiki/intro",
    {
      type: "category",
      label: "Technical Writing",
      items: [{ type: "autogenerated", dirName: "wiki/technicalWriting" }],
    },
    {
      type: "category",
      label: "CS",
      items: [
        {
          type: "category",
          label: "Git",
          items: [{ type: "autogenerated", dirName: "wiki/git" }],
        },
        {
          type: "category",
          label: "Linux",
          items: [{ type: "autogenerated", dirName: "wiki/linux" }],
        },
      ],
    },
    {
      type: "category",
      label: "프론트엔드",
      items: [
        {
          type: "category",
          label: "CSS",
          items: [{ type: "autogenerated", dirName: "wiki/css" }],
        },
        {
          type: "category",
          label: "Javascript",
          items: [{ type: "autogenerated", dirName: "wiki/javascript" }],
        },
        {
          type: "category",
          label: "React",
          items: [{ type: "autogenerated", dirName: "wiki/react" }],
        },
        {
          type: "category",
          label: "Web",
          items: [{ type: "autogenerated", dirName: "wiki/web" }],
        },
      ],
    },
  ],
};

module.exports = sidebars;
